services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backoffice:
    build: ./src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./src/uploads:/app/uploads
      - ./src/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017/eu-digital
